'use client'

import { AnimatePresence, motion } from 'motion/react'
import { useState } from 'react'
import { MagnifyingGlassIcon, PlusIcon, XIcon } from '@phosphor-icons/react'
import {
  candidateToTrack,
  expandSoundCloudSet,
  expandYouTubePlaylist,
  hasYouTubeKey,
  parseSourceUrl,
  resolveSoundCloud,
  resolveSpotifyMeta,
  resolveYouTubeVideo,
  searchYouTube,
  type MatchCandidate,
} from '@/lib/sources'
import type { Track } from '@/lib/types'
import { Button, SourceBadge, spring } from './ui'

type Stage =
  | { kind: 'idle' }
  | { kind: 'working'; message: string }
  | { kind: 'preview'; tracks: Track[]; label: string }
  | { kind: 'picker'; title: string; thumbnail: string | null; candidates: MatchCandidate[] }
  | { kind: 'spotify-manual'; title: string; thumbnail: string | null; reason: string }
  | { kind: 'error'; message: string; hint?: string }

export function AddToQueue({
  onAdd,
  username,
}: {
  onAdd: (tracks: Track[]) => void
  username: string
}) {
  const [value, setValue] = useState('')
  const [stage, setStage] = useState<Stage>({ kind: 'idle' })

  const reset = () => {
    setStage({ kind: 'idle' })
    setValue('')
  }

  async function handleSubmit(raw: string) {
    const parsed = parseSourceUrl(raw)

    try {
      switch (parsed.kind) {
        case 'yt-video': {
          setStage({ kind: 'working', message: 'looking that up…' })
          const track = await resolveYouTubeVideo(parsed.videoId, username)
          if (!track) {
            setStage({
              kind: 'error',
              message: "Couldn't load that video",
              hint: 'It may be private, deleted, or blocked from embedding.',
            })
            return
          }
          setStage({ kind: 'preview', tracks: [track], label: '1 track' })
          return
        }

        case 'yt-video-in-playlist':
        case 'yt-playlist': {
          // Both shapes carry the list id; a watch?v=…&list=… link expands the whole playlist.
          const playlistId = parsed.playlistId
          setStage({ kind: 'working', message: 'unpacking the playlist…' })
          const tracks = await expandYouTubePlaylist(playlistId, username, (done, total) => {
            setStage({ kind: 'working', message: `unpacking… ${done}/${total}` })
          })
          if (tracks.length === 0) {
            setStage({
              kind: 'error',
              message: "That playlist came back empty",
              hint: 'Private playlists and mixes auto-generated by YouTube often will not expand.',
            })
            return
          }
          setStage({ kind: 'preview', tracks, label: `${tracks.length} tracks` })
          return
        }

        case 'sc-track': {
          setStage({ kind: 'working', message: 'looking that up…' })
          const track = await resolveSoundCloud(parsed.url, username)
          if (!track) {
            setStage({
              kind: 'error',
              message: "Couldn't load that SoundCloud track",
              hint: 'Private and region-locked tracks cannot be embedded.',
            })
            return
          }
          setStage({ kind: 'preview', tracks: [track], label: '1 track' })
          return
        }

        case 'sc-set': {
          setStage({ kind: 'working', message: 'unpacking the set…' })
          const tracks = await expandSoundCloudSet(parsed.url, username)
          if (tracks.length === 0) {
            setStage({ kind: 'error', message: 'That set came back empty' })
            return
          }
          setStage({ kind: 'preview', tracks, label: `${tracks.length} tracks` })
          return
        }

        case 'sc-short':
          setStage({
            kind: 'error',
            message: 'Short SoundCloud links need unwrapping',
            hint: 'Open the on.soundcloud.com link, then paste the full soundcloud.com/… address.',
          })
          return

        case 'sp-short':
          setStage({
            kind: 'error',
            message: 'Short Spotify links need unwrapping',
            hint: 'Open the spotify.link, then paste the full open.spotify.com/… address.',
          })
          return

        case 'sp': {
          await handleSpotify(parsed.url, parsed.spKind)
          return
        }

        default:
          setStage({
            kind: 'error',
            message: "That doesn't look like a link we know",
            hint: 'YouTube, SoundCloud and Spotify links work — tracks or playlists.',
          })
      }
    } catch (err) {
      setStage({
        kind: 'error',
        message: 'That did not go to plan',
        hint: err instanceof Error ? err.message : undefined,
      })
    }
  }

  async function handleSpotify(url: string, spKind: string) {
    setStage({ kind: 'working', message: 'asking Spotify politely…' })
    const meta = await resolveSpotifyMeta(url)

    if (!meta) {
      setStage({
        kind: 'error',
        message: "Couldn't read that Spotify link",
        hint: 'Double-check it opens in a browser.',
      })
      return
    }

    if (spKind !== 'track' && spKind !== 'episode') {
      // oEmbed returns one title for the whole album/playlist and no track list at all.
      setStage({
        kind: 'spotify-manual',
        title: meta.title,
        thumbnail: meta.thumbnail,
        reason:
          'Spotify only tells us the name of an album or playlist, never what is inside it. Add the tracks you want one at a time, or paste a YouTube playlist instead.',
      })
      return
    }

    if (!hasYouTubeKey()) {
      setStage({
        kind: 'spotify-manual',
        title: meta.title,
        thumbnail: meta.thumbnail,
        reason:
          'Spotify needs Premium on every listener’s account to play here, so we match tracks to YouTube instead. That needs a YouTube API key, which is not set up.',
      })
      return
    }

    setStage({ kind: 'working', message: 'hunting for a match on YouTube…' })
    try {
      const candidates = await searchYouTube(meta.title)
      if (candidates.length === 0) {
        setStage({
          kind: 'spotify-manual',
          title: meta.title,
          thumbnail: meta.thumbnail,
          reason: 'We searched YouTube and came up empty.',
        })
        return
      }
      setStage({
        kind: 'picker',
        title: meta.title,
        thumbnail: meta.thumbnail,
        candidates,
      })
    } catch (err) {
      const quota = err instanceof Error && err.message === 'quota'
      setStage({
        kind: 'spotify-manual',
        title: meta.title,
        thumbnail: meta.thumbnail,
        reason: quota
          ? "Today's YouTube search quota is used up. It resets at midnight US Pacific time."
          : 'The YouTube search failed.',
      })
    }
  }

  return (
    <div className="flex flex-col gap-3">
      <form
        onSubmit={(e) => {
          e.preventDefault()
          const raw = value.trim()
          if (raw) void handleSubmit(raw)
        }}
        className="flex gap-2"
      >
        <input
          value={value}
          onChange={(e) => setValue(e.target.value)}
          placeholder="paste a link…"
          aria-label="Paste a YouTube, SoundCloud or Spotify link"
          className="input-chunk flex-1"
          inputMode="url"
          autoComplete="off"
          spellCheck={false}
        />
        <Button
          tone="lilac"
          type="submit"
          icon
          disabled={!value.trim() || stage.kind === 'working'}
          aria-label="Add to queue"
        >
          <PlusIcon size={24} weight="bold" />
        </Button>
      </form>

      <AnimatePresence mode="popLayout">
        {stage.kind !== 'idle' && (
          <motion.div
            key={stage.kind}
            initial={{ opacity: 0, y: -8, scale: 0.98 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: -8, scale: 0.98 }}
            transition={spring}
            className="card-flat p-3"
          >
            {stage.kind === 'working' && (
              <p className="flex items-center gap-2 py-1 text-sm font-extrabold text-ink">
                <MagnifyingGlassIcon size={18} weight="bold" className="spinning" />
                {stage.message}
              </p>
            )}

            {stage.kind === 'preview' && (
              <div className="flex flex-col gap-3">
                <div className="flex items-center gap-3">
                  {stage.tracks[0].thumbnail && (
                    // eslint-disable-next-line @next/next/no-img-element
                    <img
                      src={stage.tracks[0].thumbnail}
                      alt=""
                      width={56}
                      height={56}
                      className="h-14 w-14 shrink-0 rounded-[14px] border-[3px] border-ink object-cover"
                    />
                  )}
                  <div className="min-w-0 flex-1">
                    <p className="truncate text-sm font-extrabold text-ink">
                      {stage.tracks[0].title}
                    </p>
                    <p className="truncate text-xs font-semibold text-ink-soft">
                      {stage.tracks[0].artist || 'unknown artist'}
                    </p>
                    <div className="mt-1 flex items-center gap-1.5">
                      <SourceBadge
                        sourceType={stage.tracks[0].sourceType}
                        matchedFrom={stage.tracks[0].matchedFrom}
                      />
                      <span className="text-[10px] font-bold text-ink-soft">{stage.label}</span>
                    </div>
                  </div>
                </div>
                <div className="flex gap-2">
                  <Button
                    tone="mint"
                    className="flex-1"
                    onClick={() => {
                      onAdd(stage.tracks)
                      reset()
                    }}
                  >
                    Add {stage.label}
                  </Button>
                  <Button tone="paper" icon onClick={reset} aria-label="Cancel">
                    <XIcon size={20} weight="bold" />
                  </Button>
                </div>
              </div>
            )}

            {stage.kind === 'picker' && (
              <div className="flex flex-col gap-2">
                <p className="text-sm font-extrabold text-ink">
                  Which one is “{stage.title}”?
                </p>
                <p className="text-xs font-semibold text-ink-soft">
                  Spotify never tells us the artist, so pick the right one — everyone hears your
                  choice.
                </p>
                {stage.candidates.map((c) => (
                  <button
                    key={c.videoId}
                    onClick={() => {
                      onAdd([candidateToTrack(c, username)])
                      reset()
                    }}
                    className="flex items-center gap-3 rounded-[16px] border-[3px] border-ink p-2 text-left"
                    style={{ background: 'var(--color-paper-sunk)' }}
                  >
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                      src={c.thumbnail}
                      alt=""
                      width={48}
                      height={48}
                      className="h-12 w-12 shrink-0 rounded-[12px] border-2 border-ink object-cover"
                    />
                    <div className="min-w-0">
                      <p className="truncate text-xs font-extrabold text-ink">{c.title}</p>
                      <p className="truncate text-[11px] font-semibold text-ink-soft">
                        {c.channel}
                      </p>
                    </div>
                  </button>
                ))}
                <Button tone="paper" onClick={reset}>
                  None of these
                </Button>
              </div>
            )}

            {stage.kind === 'spotify-manual' && (
              <div className="flex flex-col gap-3">
                <div className="flex items-center gap-3">
                  {stage.thumbnail && (
                    // eslint-disable-next-line @next/next/no-img-element
                    <img
                      src={stage.thumbnail}
                      alt=""
                      width={56}
                      height={56}
                      className="h-14 w-14 shrink-0 rounded-[14px] border-[3px] border-ink object-cover"
                    />
                  )}
                  <div className="min-w-0">
                    <p className="truncate text-sm font-extrabold text-ink">{stage.title}</p>
                    <p className="text-xs font-semibold text-ink-soft">from Spotify</p>
                  </div>
                </div>
                <p className="text-xs font-semibold text-ink-soft">{stage.reason}</p>
                <div className="flex gap-2">
                  <a
                    href={`https://www.youtube.com/results?search_query=${encodeURIComponent(stage.title)}`}
                    target="_blank"
                    rel="noreferrer noopener"
                    className="flex-1"
                  >
                    <Button tone="sun" className="w-full">
                      Find it on YouTube
                    </Button>
                  </a>
                  <Button tone="paper" icon onClick={reset} aria-label="Dismiss">
                    <XIcon size={20} weight="bold" />
                  </Button>
                </div>
              </div>
            )}

            {stage.kind === 'error' && (
              <div className="flex flex-col gap-2">
                <p className="text-sm font-extrabold text-ink">{stage.message}</p>
                {stage.hint && (
                  <p className="text-xs font-semibold text-ink-soft">{stage.hint}</p>
                )}
                <Button tone="paper" onClick={reset}>
                  Try another link
                </Button>
              </div>
            )}
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}
